version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: BankDB
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bankapp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-uroot","-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always    

  bankapp:
    image: deepanshub9/bankapp-springboot:latest
    container_name: bankapp
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/BankDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_PASSWORD: Test@123
    ports:
      - "8080:8080"
    depends_on:
      -  mysql
    networks:
      - bankapp
    restart: always

networks:
  bankapp:

volumes:
  mysql-data:
